name: Deploy to CF worker

# Controls when the workflow will run
on:
  push:
    branches: [main]

  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: barber-bot
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  NODE_VERSION: "12.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Resolve Project Dependencies Using Npm"
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build
          popd

      - name: Azure Functions Action
        uses: Azure/functions-action@v1.4.3
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
